/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CoastRiver(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/CoastRiver.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh material={materials.GrayMam} geometry={nodes.RightCoast_1.geometry} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh material={materials.GrayMam} geometry={nodes.LeftCoast_1.geometry} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh material={materials.BlueMat} geometry={nodes.River_1.geometry} />
        </group>
        <group position={[0, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh material={materials.WgiteMap} geometry={nodes.LeftBordur_1.geometry} />
        </group>
        <group position={[0, 0, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh material={materials.WgiteMap} geometry={nodes.RightBordur_1.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CoastRiver.gltf')
